apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#Quando ele for customizar algo, ele irá ler os 2 arquivos
#abaixo:
resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: ebomfim/gitops01
  newTag: d5fb3874e29e02ebb22991421f84ad74806e7da3
