apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#Quando ele for customizar algo, ele irá ler os 2 arquivos
#abaixo:
resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: ebomfim/gitops01
  newTag: 0a516c09274760e89ce855d4f2eb44d9dca1d6d5
