apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#Quando ele for customizar algo, ele irá ler os 2 arquivos
#abaixo:
resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: ebomfim/gitops01
  newTag: 7b67581a5ee0217f21ea881d87c21a17b1e5f17a
